// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SM_BE.Data;

#nullable disable

namespace sm_be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250729110015_AddMoneyTransactions")]
    partial class AddMoneyTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SM_BE.Models.Lottery.DailyNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("WinningNumber")
                        .HasColumnType("int")
                        .HasColumnName("winning_number");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("daily_numbers", (string)null);
                });

            modelBuilder.Entity("SM_BE.Models.Lottery.PlayerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DailyNumberId")
                        .HasColumnType("int")
                        .HasColumnName("daily_number_id");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("entry_time");

                    b.Property<int>("GuessedNumber")
                        .HasColumnType("int")
                        .HasColumnName("guessed_number");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_winner");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyNumberId");

                    b.HasIndex("UserId", "DailyNumberId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerEntries_UserId_DailyNumberId");

                    b.ToTable("player_entries", (string)null);
                });

            modelBuilder.Entity("SM_BE.Models.MoneyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("GameId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("game_id");

                    b.Property<string>("GameType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("game_type");

                    b.Property<decimal>("InGameMoneyAfter")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("in_game_money_after");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("money_type");

                    b.Property<decimal>("RealMoneyAfter")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("real_money_after");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("reference_id");

                    b.Property<string>("TransactionDirection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("transaction_direction");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_MoneyTransactions_CreatedAt");

                    b.HasIndex("GameType")
                        .HasDatabaseName("IX_MoneyTransactions_GameType");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("IX_MoneyTransactions_ReferenceId");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("IX_MoneyTransactions_TransactionType");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MoneyTransactions_UserId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_MoneyTransactions_UserId_CreatedAt");

                    b.ToTable("money_transactions", (string)null);
                });

            modelBuilder.Entity("SM_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SM_BE.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowMessaging")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_messaging");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int")
                        .HasColumnName("current_streak");

                    b.Property<int>("DailyNumberGamesPlayed")
                        .HasColumnType("int")
                        .HasColumnName("daily_number_games_played");

                    b.Property<int>("DailyNumberWins")
                        .HasColumnType("int")
                        .HasColumnName("daily_number_wins");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("DigitGameWins")
                        .HasColumnType("int")
                        .HasColumnName("digit_game_wins");

                    b.Property<int>("DigitGamesPlayed")
                        .HasColumnType("int")
                        .HasColumnName("digit_games_played");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int")
                        .HasColumnName("experience_points");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("facebook_url");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<decimal>("InGameMoney")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("in_game_money");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("instagram_url");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_phone_verified");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_profile_complete");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_active_at");

                    b.Property<DateTime?>("LastGamePlayedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_game_played_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("linkedin_url");

                    b.Property<int>("LongestLoseStreak")
                        .HasColumnType("int")
                        .HasColumnName("longest_lose_streak");

                    b.Property<int>("LongestWinStreak")
                        .HasColumnType("int")
                        .HasColumnName("longest_win_streak");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PreferredGameMode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("preferred_game_mode");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_picture_url");

                    b.Property<decimal>("RealMoney")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("real_money");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("receive_email_notifications");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("receive_notifications");

                    b.Property<bool>("ReceiveSmsNotifications")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("receive_sms_notifications");

                    b.Property<bool>("ShowDateOfBirth")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_date_of_birth");

                    b.Property<bool>("ShowEmail")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_email");

                    b.Property<bool>("ShowLocation")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_location");

                    b.Property<bool>("ShowOnlineStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_online_status");

                    b.Property<bool>("ShowPhoneNumber")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_phone_number");

                    b.Property<bool>("ShowSocialLinks")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_social_links");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("time_zone");

                    b.Property<int>("TotalAchievements")
                        .HasColumnType("int")
                        .HasColumnName("total_achievements");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("int")
                        .HasColumnName("total_games_played");

                    b.Property<int>("TotalLosses")
                        .HasColumnType("int")
                        .HasColumnName("total_losses");

                    b.Property<int>("TotalWins")
                        .HasColumnType("int")
                        .HasColumnName("total_wins");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("twitter_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.Property<decimal>("WinPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("win_percentage");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("sm_be.Models.MinimumNumberCount.DailyDigitGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_completed");

                    b.Property<int?>("WinningDigit")
                        .HasColumnType("int")
                        .HasColumnName("winning_digit");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("daily_digit_games", (string)null);
                });

            modelBuilder.Entity("sm_be.Models.MinimumNumberCount.PlayerDigitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DailyDigitGameId")
                        .HasColumnType("int")
                        .HasColumnName("daily_digit_game_id");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("entry_time");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_winner");

                    b.Property<int>("SelectedDigit")
                        .HasColumnType("int")
                        .HasColumnName("selected_digit");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyDigitGameId");

                    b.HasIndex("UserId", "DailyDigitGameId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerDigitEntries_UserId_DailyDigitGameId");

                    b.ToTable("player_digit_entries", (string)null);
                });

            modelBuilder.Entity("SM_BE.Models.Lottery.PlayerEntry", b =>
                {
                    b.HasOne("SM_BE.Models.Lottery.DailyNumber", "DailyNumber")
                        .WithMany("PlayerEntries")
                        .HasForeignKey("DailyNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerEntries_DailyNumbers");

                    b.HasOne("SM_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerEntries_Users");

                    b.Navigation("DailyNumber");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SM_BE.Models.MoneyTransaction", b =>
                {
                    b.HasOne("SM_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MoneyTransactions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SM_BE.Models.UserProfile", b =>
                {
                    b.HasOne("SM_BE.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("SM_BE.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserProfiles_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sm_be.Models.MinimumNumberCount.PlayerDigitEntry", b =>
                {
                    b.HasOne("sm_be.Models.MinimumNumberCount.DailyDigitGame", "DailyDigitGame")
                        .WithMany("PlayerDigitEntries")
                        .HasForeignKey("DailyDigitGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerDigitEntries_DailyDigitGames");

                    b.HasOne("SM_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerDigitEntries_Users");

                    b.Navigation("DailyDigitGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SM_BE.Models.Lottery.DailyNumber", b =>
                {
                    b.Navigation("PlayerEntries");
                });

            modelBuilder.Entity("sm_be.Models.MinimumNumberCount.DailyDigitGame", b =>
                {
                    b.Navigation("PlayerDigitEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
