// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SM_BE.Data;

#nullable disable

namespace sm_be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250724124242_AddDailyDigitGame")]
    partial class AddDailyDigitGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SM_BE.Models.Lottery.DailyNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("WinningNumber")
                        .HasColumnType("int")
                        .HasColumnName("winning_number");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("daily_numbers", (string)null);
                });

            modelBuilder.Entity("SM_BE.Models.Lottery.PlayerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DailyNumberId")
                        .HasColumnType("int")
                        .HasColumnName("daily_number_id");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("entry_time");

                    b.Property<int>("GuessedNumber")
                        .HasColumnType("int")
                        .HasColumnName("guessed_number");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_winner");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyNumberId");

                    b.HasIndex("UserId", "DailyNumberId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerEntries_UserId_DailyNumberId");

                    b.ToTable("player_entries", (string)null);
                });

            modelBuilder.Entity("SM_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("sm_be.Models.MinimumNumberCount.DailyDigitGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_completed");

                    b.Property<int?>("WinningDigit")
                        .HasColumnType("int")
                        .HasColumnName("winning_digit");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("daily_digit_games", (string)null);
                });

            modelBuilder.Entity("sm_be.Models.MinimumNumberCount.PlayerDigitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DailyDigitGameId")
                        .HasColumnType("int")
                        .HasColumnName("daily_digit_game_id");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("entry_time");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_winner");

                    b.Property<int>("SelectedDigit")
                        .HasColumnType("int")
                        .HasColumnName("selected_digit");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DailyDigitGameId");

                    b.HasIndex("UserId", "DailyDigitGameId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerDigitEntries_UserId_DailyDigitGameId");

                    b.ToTable("player_digit_entries", (string)null);
                });

            modelBuilder.Entity("SM_BE.Models.Lottery.PlayerEntry", b =>
                {
                    b.HasOne("SM_BE.Models.Lottery.DailyNumber", "DailyNumber")
                        .WithMany("PlayerEntries")
                        .HasForeignKey("DailyNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerEntries_DailyNumbers");

                    b.HasOne("SM_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerEntries_Users");

                    b.Navigation("DailyNumber");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sm_be.Models.MinimumNumberCount.PlayerDigitEntry", b =>
                {
                    b.HasOne("sm_be.Models.MinimumNumberCount.DailyDigitGame", "DailyDigitGame")
                        .WithMany("PlayerDigitEntries")
                        .HasForeignKey("DailyDigitGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerDigitEntries_DailyDigitGames");

                    b.HasOne("SM_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerDigitEntries_Users");

                    b.Navigation("DailyDigitGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SM_BE.Models.Lottery.DailyNumber", b =>
                {
                    b.Navigation("PlayerEntries");
                });

            modelBuilder.Entity("sm_be.Models.MinimumNumberCount.DailyDigitGame", b =>
                {
                    b.Navigation("PlayerDigitEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
